# Generated by Django 2.1.3 on 2018-11-06 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgrade', models.CharField(max_length=20)),
                ('cnum', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cls',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('bage', models.CharField(max_length=20)),
                ('bdate', models.DateField()),
                ('isDelete', models.BooleanField(default=False)),
                ('bcls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Cls')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
